steps:
- bash: |
    echo ""
    echo "--------------------------------"
    echo "Confirm Key Vault 🔑 Integration"
    echo "--------------------------------"
    echo "KV_DEBUG_ENV: $KV_DEBUG_ENV"
    echo ""
    if [ "$KV_DEBUG_ENV" = '$(kv-debug-env)' ]; then
      echo "⛔️ Key Vault not loaded. Please double check configuration:"
      echo "- Azure Pipelines UI: secret added to Library Group"
      echo "- YAML: pipeline run is on `main` or `production`."
      exit 1
    else
      echo "✅ Key Vault loaded."
    fi
  displayName: Debug - Key Vault loaded?
  env:
    KV_DEBUG_ENV: $(kv-debug-env)
